# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cogitator < Formula
  desc "Monitor local opencode instances from a single TUI"
  homepage "https://github.com/guilhermehto/cogitator"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guilhermehto/cogitator/releases/download/v0.2.0/cogitator_0.2.0_darwin_amd64.tar.gz"
      sha256 "7b37dcdfd279d4e7ca0824e3669b3906561e305d3ccbc8702174de9894ed9ecb"

      define_method(:install) do
        bin.install "cogitator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guilhermehto/cogitator/releases/download/v0.2.0/cogitator_0.2.0_darwin_arm64.tar.gz"
      sha256 "1cebbe8a6391ea90d98dd9f749fb3ca8cf84386a83c7989d0bf9ddb468c7345e"

      define_method(:install) do
        bin.install "cogitator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guilhermehto/cogitator/releases/download/v0.2.0/cogitator_0.2.0_linux_amd64.tar.gz"
      sha256 "80701938d05028132d97c1968d5b1df450d179c38ce46d4b5d64b0af64e72f5e"
      define_method(:install) do
        bin.install "cogitator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guilhermehto/cogitator/releases/download/v0.2.0/cogitator_0.2.0_linux_arm64.tar.gz"
      sha256 "8f5d92e23a6ab914a4e27dd7999e33ba075f1ceff04a6ff4cb3682a8a0e49cb2"
      define_method(:install) do
        bin.install "cogitator"
      end
    end
  end

  test do
    system "#{bin}/cogitator", "--status"
  end
end
