# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cogitator < Formula
  desc "Monitor local opencode instances from a single TUI"
  homepage "https://github.com/guilhermehto/cogitator"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guilhermehto/cogitator/releases/download/v0.1.0/cogitator_0.1.0_darwin_amd64.tar.gz"
      sha256 "48c3645dc685c04b6085f2a8c31391605e49e2a219a3ea07fcfe23a876c017e5"

      define_method(:install) do
        bin.install "cogitator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guilhermehto/cogitator/releases/download/v0.1.0/cogitator_0.1.0_darwin_arm64.tar.gz"
      sha256 "4adf3d51ebcb2c1803ef08be1edabf11549f9952f0762668e1650ac7d9d85eec"

      define_method(:install) do
        bin.install "cogitator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guilhermehto/cogitator/releases/download/v0.1.0/cogitator_0.1.0_linux_amd64.tar.gz"
      sha256 "e08d18f9b7f8ae6fe94f94bc9fafa38be35f221ddaa83ab140a210494c424f25"
      define_method(:install) do
        bin.install "cogitator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guilhermehto/cogitator/releases/download/v0.1.0/cogitator_0.1.0_linux_arm64.tar.gz"
      sha256 "9a65281137f978a90303b9894e400a03cf7f53a272cd001113cb3336a2cbddb1"
      define_method(:install) do
        bin.install "cogitator"
      end
    end
  end

  test do
    system "#{bin}/cogitator", "--status"
  end
end
